const {
    NEXT_PUBLIC_PHONE,
    NEXT_PUPLIC_EMAIL,
    NEXT_PUPLIC_ADDRESS,
    NEXT_PUBLIC_FACEBOOK,
    NEXT_PUBLIC_LINKEDIN,
    NEXT_PUBLIC_INSTAGRAM,
    NEXT_PUBLIC_YOUTUBE,
    NEXT_PUBLIC_TWITTER,
    NEXT_PUBLIC_PINTEREST,
    NEXT_PUBLIC_GOOGLE_PLUS,
    NEXT_PUBLIC_BLOGSPOT,
} = process.env;

export const PHONE = NEXT_PUBLIC_PHONE;
export const EMAIL = NEXT_PUPLIC_EMAIL;
export const ADDRESS = NEXT_PUPLIC_ADDRESS;

export const FACEBOOK = NEXT_PUBLIC_FACEBOOK;
export const LINKEDIN = NEXT_PUBLIC_LINKEDIN;
export const INSTAGRAM = NEXT_PUBLIC_INSTAGRAM;
export const YOUTUBE = NEXT_PUBLIC_YOUTUBE;
export const TWITTER = NEXT_PUBLIC_TWITTER;
export const PINTEREST = NEXT_PUBLIC_PINTEREST;
export const GOOGLE_PLUS = NEXT_PUBLIC_GOOGLE_PLUS;
export const BLOGSPOT = NEXT_PUBLIC_BLOGSPOT;
